# Generated by Django 4.0.2 on 2022-02-27 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_module_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='user',
        ),
    ]
